version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/taskmanagement?schema=public
      - JWT_SECRET=dev-secret-key
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskmanagement
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: